### ISSUE TITLE
 ROS time moved backwards

### ISSUE THREAD

**Issue by LanxinL** [Acmece/rl-collision-avoidance#8]
Hi, I get the following error when I run `mpiexec -np 50 python circle_test.py`

```
[ERROR] [1586937246.001479, 18.100000]: ROS time moved backwards: 4165.032s
Traceback (most recent call last):
  File "circle_test.py", line 94, in <module>
    env = StageWorld(OBS_SIZE, index=rank, num_env=NUM_ENV)
  File "/code/rl-collision-avoidance/circle_world.py", line 76, in __init__
    rospy.sleep(1.)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/timer.py", line 164, in sleep
    raise rospy.exceptions.ROSTimeMovedBackwardsException(time_jump)
rospy.exceptions.ROSTimeMovedBackwardsException: ROS time moved backwards
```

**Comment by Acmece** [comment]
I didn't meet this problem in the past. I guess there are other ros-related programs running(roscore etc ..).
Could you please check it and test it again?
